### ISSUE TITLE
ImportError: sys.meta_path is None, Python is likely shutting down

### ISSUE THREAD

**Issue by sbor23** [psychopy/psychopy#1816]
Hi

On a fresh Python 3 install using pip on Windows 10 we get the following exceptions after the (very basic) experiment finished successfully (seemingly):

```python
Exception ignored in: <bound method ImageStim.__del__ of <psychopy.visual.image.ImageStim object at 0x00000276E3372358>>
Traceback (most recent call last):
  File "C:\Users\stbo\.virtualenvs\PsychoPy2-v3RNEhUT\lib\site-packages\psychopy\visual\image.py", line 238, in __del__
  File "C:\Users\stbo\.virtualenvs\PsychoPy2-v3RNEhUT\lib\site-packages\pyglet\gl\lib.py", line 97, in errcheck
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <bound method TextStim.__del__ of <psychopy.visual.text.TextStim object at 0x00000276E3372978>>
Traceback (most recent call last):
  File "C:\Users\stbo\.virtualenvs\PsychoPy2-v3RNEhUT\lib\site-packages\psychopy\visual\text.py", line 177, in __del__
  File "C:\Users\stbo\.virtualenvs\PsychoPy2-v3RNEhUT\lib\site-packages\pyglet\gl\lib.py", line 97, in errcheck
ImportError: sys.meta_path is None, Python is likely shutting down
[...]
```

It seems like there is no impact on the experiment itself, it just spams the console after the experiment finished.
Looks like some kind of threading problem in pyglet?

**Comment by hoechenberger** [comment]
Can you provide a [minimal working example](https://stackoverflow.com/help/mcve) please?

**Comment by EruIluvatar** [comment]
It looks like it's tied to RatingScale.
I reduced it so much that the exception in `<bound method ImageStim.__del__ of <psychopy.visual.image.ImageStim object at ...>` doesn't occur anymore for some reason, but TextStim still does.

Removing the `from psychopy import event` line get's rid of the exceptions, so does the removal of `ratingscales = RatingScale(...)`

```Python
# try toggling the next line:
from psychopy import event
from psychopy.visual import Window, RatingScale

### Screen config
XRES = 900
YRES = 900

### Construct experiment
if __name__ == '__main__':
    # create window and mouse objects
    window = Window((XRES, YRES), allowGUI=False, color='black', fullscr=False,
                         monitor='testMonitor', winType='pyglet', units='pix')

    ratingscales = RatingScale(win=window,
                    name='valence_rating',
                    scale='Wie fühlen Sie sich gerade?',
                    stretch=2,
                    pos=[0.0, -0.4],
                    low=0,
                    high=1,
                    precision=100,
                    showValue=False,
                    markerExpansion=0,
                    acceptText='Weiter',
                    textColor='white',
                    labels=('negativ', 'positiv'))
```

**Comment by peircej** [comment]
Thanks, I can replicate that on standalone Py3 (Py2 seems fine). For some reason the RatingScale is staying alive so long that, on shutdown. pyglet.gl has been garbage collected before RatingScale, which is a problem because RatingScale *needs* gl in order to delete itself.

1. Easy workaround:

Delete your RatingScale manually before the script ends using `del ratingscales`

2. Better:

We could set register a method for 'atexit' so that ratingscales delete themselves earlier on in the shutdwon process.

3. Ideal (but hard):

Work out why RatingScale is hanging around so long in Py3 and fix it. But then **also** do option 2 to be certain!

**Comment by hoechenberger** [comment]
I managed to reproduce that with a very simple MWE. This is psychopy `master`, Python 3.6.5, pyglet 1.3.2, running on macOS.

Working as intended:
```python
from psychopy import visual

win = visual.Window()
t = visual.TextStim(win)
```
Produces:
```python
/Users/hoechenberger/miniconda3/envs/psychopy/bin/python /Users/hoechenberger/Library/Preferences/PyCharm2018.1/scratches/scratch_4.py
1.0291 	WARNING 	Monitor specification not found. Creating a temporary one...

Process finished with exit code 0
```

Look what happens if I import `event` before `visual`:
```python
from psychopy import event, visual

win = visual.Window()
t = visual.TextStim(win)
```
Produces:
```python
/Users/hoechenberger/miniconda3/envs/psychopy/bin/python /Users/hoechenberger/Library/Preferences/PyCharm2018.1/scratches/scratch_4.py
1.0165 	WARNING 	Monitor specification not found. Creating a temporary one...
Exception ignored in: <bound method TextStim.__del__ of <psychopy.visual.text.TextStim object at 0x121eb6b38>>
Traceback (most recent call last):
  File "/Users/hoechenberger/Development/psychopy/psychopy/visual/text.py", line 177, in __del__
  File "/Users/hoechenberger/miniconda3/envs/psychopy/lib/python3.6/site-packages/pyglet/gl/lib.py", line 97, in errcheck
ModuleNotFoundError: import of pyglet halted; None in sys.modules

Process finished with exit code 0
```

When `event` imported after `visual`, all is good again:
```python
from psychopy import visual, event

win = visual.Window()
t = visual.TextStim(win)
```
Produces:
```python
/Users/hoechenberger/miniconda3/envs/psychopy/bin/python /Users/hoechenberger/Library/Preferences/PyCharm2018.1/scratches/scratch_4.py
1.0805 	WARNING 	Monitor specification not found. Creating a temporary one...
```

**Comment by hoechenberger** [comment]
Explicitly `del`ing the `TextStim`, as suggested by @peircej, also works around the issue:
```python
from psychopy import event, visual

win = visual.Window()
t = visual.TextStim(win)
del t
```
Produces:
```python
/Users/hoechenberger/miniconda3/envs/psychopy/bin/python /Users/hoechenberger/Library/Preferences/PyCharm2018.1/scratches/scratch_4.py
1.0070 	WARNING 	Monitor specification not found. Creating a temporary one...

Process finished with exit code 0
```

**Comment by EruIluvatar** [comment]
Ok good to know it's not only on my side.
I will try both options and report back tomorrow.
Thanks for the suggestions.

**Comment by EruIluvatar** [comment]
Importing `visual` first and then `event` works well in our experiment.
Using `del ratingscales` does work as well, but there are more exceptions thrown by other stimuli, in this case `ImageStim` and `TextStim` (which I dropped out of the exaple above).

**Comment by peircej** [comment]
OK, this must be to do with the order of garbage collection, and interesting that it's affected by order of initialisation (well, maybe that does make sense). I guess if event was imported second (and it includes pyglet) then it prevents pyglet being garbage collected too early and so no error message.

The solution that we've now implemented for a few things is to register an atexit function during init as done for Window class 54427067771. The atexit call gets run before other objects are deleted, so it ensures that it's cleaned up before any of the critical modules have been cleaned up. This should be done *in conjunction* with `__del__` functions because the latter is still needed to clean up when the an object is deleted/reassigned within the script.

**Comment by NaturallyAsh** [comment]
Also, I just wanted to mention that I had `from psychopy.hardware import keyboard` before `from psychopy import visual, core,` etc. and was still getting the aforementioned error.  Switching those lines, with `from psychopy` first, removed the error.  The order didn't cause an error to pop up on the standalone, but only when I ran it from PyCharm.  Maybe this will help someone.

**Comment by mdcutone** [comment]
Could it be related to lazy loading?
