### ISSUE TITLE
Installation issue under Windows 7

### ISSUE THREAD

**Issue by dfkettle** [psychopy/psychopy#2267]
Hi! I don't know if this is a bug in PsychoPy or just an installation issue. I posted this in the PsychoPy forum a few days ago, but so far nobody has responded, so I thought I'd try here.

I downloaded and installed PsychoPy v3.0 using the standalone version (StandalonePsychoPy3-3.0.2-win32.exe to be exact) under Windows 7 SP 1, but when I try to start it, nothing happens. Literally, nothing happens, no error message, nothing. I thought there might be a conflict with Anaconda, which I already had installed. After a little investigation, I found that my installation of Anaconda is using Python 3.6.7, and PsychoPy is using Python 3.6.5. So I removed all entries for Anaconda from the path (which preceded the path entries for PsychoPy) and tried to start it from the command line (so I could see any error messages), but still nothing happened, not even any error messages. 

Here is a link to a screenshot: https://www.dropbox.com/s/yuh8ctz61quy5yi/Screenshot%202019-02-09%2016.06.19.png?dl=0

Maybe my video card isn’t compatible, but shouldn’t I see some sort of error message at least? Any suggestions?
Thanks.

**Comment by dvbridges** [comment]
Hi @dfkettle, thank you for your patience. Does version 3.0.1 install and run correctly?

**Comment by peircej** [comment]
I can't find your post on the forum but the general advice is here:
https://www.psychopy.org/troubleshooting.html

Most likely an error message is occurring but being swallowed before you got to see it. Could you open a command line and paste in this (note that your installation might be in a different Program Files folder):
`"C:\Program Files\PsychoPy2\python.exe" -m psychopy.app.psychopyApp`

That should give you an error message and we can take it from there.

cheers

**Comment by hoechenberger** [comment]
Isn't that what they did already, according to the screenshot?

**Comment by peircej** [comment]
Ah, apologies. I think the command used (pythonw.exe) is the reason that no output is appearing. pythonw tells the OS that now output is expected so doesn't provide an outlet for stderr.

You could try my command or repeat your but with python.exe instead of pythonw.exe

**Comment by hoechenberger** [comment]
Thanks @peircej, learned something new :)

**Comment by dfkettle** [comment]
You're right, there were some error messages that I didn't see, I guess because I used pythonw instead of python. Unfortunately, I don't really understand them, but here's a link to them: https://www.dropbox.com/s/aw7k5tzkswajivr/psychopy.txt?dl=0

By the way, my original post in the forum is under the Builder category. At first I had it under "Other", but since I didn't receive any response, I moved it to "Builder". Maybe it would be helpful add a category for installation issues. Anyway, here it is: https://discourse.psychopy.org/t/installation-issue-under-windows-7/6518

Thanks,
David.

**Comment by hoechenberger** [comment]
Thank you! Would it be possible for you to add the screenshots to your comments by simply dragging the files into the comment form? That way, they would be archived along with the issue description, which could help other users in the future   Typically, Dropbox links won’t be functional anymore by that time. :)

**Comment by dfkettle** [comment]
Here are the error messages. The original screen print isn't of much use, since no messages were displayed.

[psychopy.txt](https://github.com/psychopy/psychopy/files/2851555/psychopy.txt)

**Comment by peircej** [comment]
Thanks. This is curious and not one I've seen that exact one before. The basic story is that the optimize lib in scipy sometimes gets tripped up by existing dll files that have been installed (it seem very sensitive to the exact version being present). I fixed a similar problem recent by providing a different version of scipy/nump (the MKL+numpy version from gohlke) in standalone, which included more of the dlls directly so that other installed software wouldn't confuse matters.

So, could you just try the 3.0.3 in case that already fixes things? Sorry, I know that means a big download/install time.

For us, another possibility is that we reduce the number of times the scipy.optimise package gets installed, since it's often the cause of this sort of trouble

**Comment by dfkettle** [comment]
Sure, I'll try v3.0.3 and let you know. But could it be caused by a conflict with my Anaconda install? I have the scipy package installed in Anaconda, too.

**Comment by peircej** [comment]
I'm certain it won't be conflicting with the anaconda scipy itself, but it is possible that anaconda has installed an incompatible dll file into system. Even then I expect not (I think conda is good at keeping it's files to itself). I imagine this machine has some other piece of half-baked written-by-scientists 😄 software that's doing something careless!

**Comment by dfkettle** [comment]
I installed 3.0.3 and also uninstalled Anaconda, but I'm still getting the same error.

**Comment by peircej** [comment]
OK, thanks. I'm building a 3.0.4 (hopefully today) where the problematic lib will only be loaded during curve fitting (e.g. monitor gamma correction) so the application will at least run.

**Comment by dfkettle** [comment]
If you want me to test it (at least the installation aspect of it) before you release it, let me know. It seems odd that I'm the only one to have this problem.

**Comment by peircej** [comment]
You could test if this install works on your machine (it's just a temporary link for testing):
http://psychopy.org/downloads/StandalonePsychoPy3-3.0.4-win32.exe

**Comment by dfkettle** [comment]
It still abends, although in a different place now.
![screenshot 2019-02-13 11 19 46](https://user-images.githubusercontent.com/8409615/52726777-d6a5fd80-2f81-11e9-9d8d-26c6230b5fd4.png)

**Comment by peircej** [comment]
OK, well the positive side is that it's good we checked first, and it looks like we can fix this :-)
To save this rather slow iteration, could you try tweaking the files locally to test again?
You can see the next fix here: https://github.com/peircej/psychopy/commit/4a237c19f06e7043be75d79289ccbfc6e584aecd

Basically, delete line 8 of data.py and then resinsert it to (at least) one of the other locations (line 226 or 236 or both) so we can confirm that in the other location it's safe from your broken system! 😄 

By the way, I'm not sure what it is about your machine that is causing scipy to be broken. I'm hoping scipy itself does at least import! Actually you could also test that too. If you simply run python in the command line, where you are int he screenshot above and try doing `import scipy` to see what happens. If that also fails then we have a few more imports to remove!

**Comment by dfkettle** [comment]
That seems to work (at least it starts up and opens the Coder and Builder windows). I moved line 8 to the line after 226. I also ran python and imported scipy with no problem. I'm currently reading "Programming Visual Illusions for Everyone", so I'll try some of the examples from the book.

I don't know why my system would be "broken", although I could have some other software installed that's causing a problem. But as far as I know, the only software I have installed which uses Python, other than Anaconda, would be Gimp and Corel Paint Shop Pro. They both use Python 2.7 internally, as a scripting engine, but I don't think there's anything in my path variable that would pick it up, and I would probably be getting a different error anyway, since I installed the Python 3 version of PsychoPy.

Here's a screen print if you want one:

![screenshot 2019-02-13 12 03 58](https://user-images.githubusercontent.com/8409615/52730069-87170000-2f88-11e9-94b8-519cd0871dcc.png)

**Comment by peircej** [comment]
OK, great. I'll build again with that change included.

Conda *might* be the issue (but then I think we'd have more people seeing it) but the software that we're clashing with isn't necessarily anything to do with another python installation. These dll files are very general libraries for maths that might be used/changed by any number of applications. That makes it hard to track down. The solution is that we need to provide our own copies of dependent libs, so we know that it won't clash.

**Comment by dfkettle** [comment]
I guess I spoke too soon. I tried running the first example from "Programming Visual Illusions for Everyone", 'KanizsaNoLoop.py', and the original error (in 'arpack.py') returned when I tried to run it. Also got a warning about a deprecated function, but I guess that's normal.

Here are the error messages, which I copied from the output tab of Builder:

Welcome to PsychoPy3!
v3.0.4
C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\app\preferencesDlg.py:289: wxPyDeprecationWarning: Call to deprecated item. Use SetToolTip instead.
  ctrls.valueCtrl.SetToolTipString(_translate(hint))

############# Running: C:\Dropbox\Python\PsychoPy\KanizsaNoLoop.py #############
Traceback (most recent call last):
  File "C:\Dropbox\Python\PsychoPy\KanizsaNoLoop.py", line 2, in <module>
    from psychopy import core,event,visual,gui
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\event.py", line 56, in <module>
    from psychopy.tools.monitorunittools import cm2pix, deg2pix, pix2cm, pix2deg
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\tools\monitorunittools.py", line 15, in <module>
    from psychopy import monitors
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\monitors\__init__.py", line 10, in <module>
    from .calibTools import *
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\monitors\calibTools.py", line 36, in <module>
    import scipy.optimize as optim
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\scipy\optimize\__init__.py", line 387, in <module>
    from ._minimize import *
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\scipy\optimize\_minimize.py", line 30, in <module>
    from ._trustregion_constr import _minimize_trustregion_constr
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\scipy\optimize\_trustregion_constr\__init__.py", line 4, in <module>
    from .minimize_trustregion_constr import _minimize_trustregion_constr
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\scipy\optimize\_trustregion_constr\minimize_trustregion_constr.py", line 4, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\scipy\sparse\linalg\__init__.py", line 117, in <module>
    from .eigen import *
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\scipy\sparse\linalg\eigen\__init__.py", line 11, in <module>
    from .arpack import *
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\scipy\sparse\linalg\eigen\arpack\__init__.py", line 22, in <module>
    from .arpack import *
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 45, in <module>
    from . import _arpack
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by peircej** [comment]
Don't worry about the tooltip deprecation warning. That won't hurt and we'll eventually fix it.

The scipy error is the same concept as before. It's being used in calibTools but only in a single place (to fit a gamma curve) so you could take that import line and move it away from the top of the script where it always gets imported, down to the function where it's actually used, so that it only gets imported if actually used.

To reiterate this is all causing the additional issue that you won't be able to fit a gamma curve, but until you need that things should work fine!

**Comment by dfkettle** [comment]
The example program from the book is very simple, it just displays four squares and a circle (the "Kanisza illusion"). I don't think it would be doing any gamma curve fitting or using calibTools (and it doesn't import scipy, either). Here's the entire text of the program:

`
import math,numpy,random
from psychopy import core,event,visual,gui

myWin = visual.Windows(color='white',units='pix',size=[1000,1000],allowGUI=False,fullscr=False)
myClock = core.Clock()


disk = visual.Circle(myWin,radius=80,fillColor='black',lineColor=None)
square = visual.Rect(myWin,width=200,height=200,fillColor='white',lineColor=None)

disk.setPos([-100,-100])
disk.draw()
disk.setPos([-100,100])
disk.draw()
disk.setPos([100,100])
disk.draw()
disk.setPos([100,-100])
disk.draw()

square.draw()

myWin.flip()

core.wait(5)
myWin.close()
core.quit()
`

I'm wondering if there's something in the Windows system registry that might be causing a problem, but I'm not sure what to look for. Do you know the name of the dll file that the error message refers to?

**Comment by dfkettle** [comment]
I found a registry entry that might be causing the problem. When you install Anaconda, it asks you if you want to "Register Anaconda as my default Python 3.7". I saw no reason not to, since I do all my Python development in Anaconda. Here's the registry entry, which I assume was created when I installed Anaconda. 

![screenshot 2019-02-14 13 04 24](https://user-images.githubusercontent.com/8409615/52807450-7c786b80-3059-11e9-98c3-eb4bdc01475f.png)

**Comment by cgohlke** [comment]
>from . import _arpack
> ImportError: DLL load failed: The specified procedure could not be found.

In my experience, this failure to load certain kind of numpy or scipy extension modules is almost always  due to the presence of outdated Intel runtime DLLs (most likely `libmmd.dll`) in the Windows system directories `C:\Windows\...`. If there is such a file, try to rename or delete it. A possible workaround for PsychoPy3 might be to explicitly load that DLL into the process (e.g. using ctypes) before importing numpy or scipy.

**Comment by dfkettle** [comment]
> > from . import _arpack
> > ImportError: DLL load failed: The specified procedure could not be found.
> 
> In my experience, this failure to load certain kind of numpy or scipy extension modules is almost always due to the presence of outdated Intel runtime DLLs (most likely `libmmd.dll`) in the Windows system directories `C:\Windows\...`. If there is such a file, try to rename or delete it. A possible workaround for PsychoPy3 might be to explicitly load that DLL into the process (e.g. using ctypes) before importing numpy or scipy.

I don't think I want to delete or rename Windows system files without knowing if they're needed by Windows. I might "break" Windows. I don't know if you read this entire thread, but the import statement is in the source code for PsychoPy, not the program I'm trying to run. 

Besides, I don't have any problem importing numpy or scipy in Anaconda, just in PsychoPy. If this dll file is causing a problem, why isn't it happening in Anaconda too?

**Comment by cgohlke** [comment]
> I don't think I want to delete or rename Windows system files

Those are Intel C or Fortran runtime files, **not** Windows system files. They should not have been installed there in the first place.

**Comment by dfkettle** [comment]
> > from . import _arpack
> > ImportError: DLL load failed: The specified procedure could not be found.
> 
> In my experience, this failure to load certain kind of numpy or scipy extension modules is almost always due to the presence of outdated Intel runtime DLLs (most likely `libmmd.dll`) in the Windows system directories `C:\Windows\...`. If there is such a file, try to rename or delete it. A possible workaround for PsychoPy3 might be to explicitly load that DLL into the process (e.g. using ctypes) before importing numpy or scipy.



> > I don't think I want to delete or rename Windows system files
> 
> Those are Intel C or Fortran runtime files, **not** Windows system files. They should not have been installed there in the first place.

I have no idea how they got installed. I found a library by that name in C:\Windows\SysWOW64, so I renamed it temporarily and tried running the PsychoPy program again. This time, I got a different error:

############# Running: C:\Dropbox\Python\PsychoPy\KanizsaNoLoop.py #############
17.8107     WARNING     Monitor specification not found. Creating a temporary one...
Traceback (most recent call last):
  File "C:\Dropbox\Python\PsychoPy\KanizsaNoLoop.py", line 4, in <module>
    myWin = visual.Windows(color='white',units='pix',size=[1000,1000],allowGUI=False,fullscr=False)
AttributeError: module 'psychopy.visual' has no attribute 'Windows'

So wherever this DLL file came from, it looks like it's required.

**Comment by dfkettle** [comment]
My mistake, there's a typo in the code, it should be 'visual.Window(...)'. It works now, so I guess 'libmmd.ddl' was the problem all along, although I don't understand why it would cause any problem, unless a function in the DDL was actually being called by PsychoPy. Thanks, @cgohlke. @peircej Maybe it isn't necessary to move the import statement in 'fit.py' after all. I'll try putting it back in its original location and see if it still works.

**Comment by dfkettle** [comment]
I moved the import statement back to its original location and it still works.

**Comment by peircej** [comment]
Many thanks for your insight @cgohlke (also thanks for your amazing packaging work!)

Minor additional explanations: PsychoPy doesn't itself need to call this library, but it calls scipy and scipy calls numerous underlying maths libs and merely loading those libs can be a problem if they're some incompatible version. If some other software package (any number of options) has installed a conflicting version of one of these libs then problems can arise. I can't tell you what software package has done it, and it might even be something you installed ages ago and then removed (if the software does the wrong thing in installing/altering a file to the system folder, then it's just as likely not to remove its files cleanly as well).

As for the PsychoPy end of things, I will leave the change to `fit` in place. As well as reducing the occurrence of these issues, it's an appropriate case for "lazy" importing where the import is large and rarely needed.

**Comment by dfkettle** [comment]
You're probably right, I've had this computer for 5 or 6 years now and I've installed and uninstalled numerous applications. I don't understand why this wasn't causing a problem in Anaconda, though. Maybe because they're using different versions of scipy. Anaconda is using v1.1.0 and PsychoPy is using v1.2.0. Or maybe because I never used that particular scipy module in Anaconda.

**Comment by hoechenberger** [comment]
Even with the DLLs present, I'm surprised PsychoPy's bundles Python is even trying to load them instead of using the shipped ones first (or does it not ship with MKL?)

`conda` installations deploy their own versions of those libraries.

**Comment by dfkettle** [comment]
> Even with those DLLs present, I'm surprised PsychoPy's bundled Python is loading them instead of the ones bundles with PsychoPy first (or does standalone not ship with MKL?)
> 
> `conda` installations deploy their own versions of those libraries.

@hoechenberger What's MKL?
